Cree Crud de escala
Bluemoonside/ProyectoEncuestaCreatividad pull request #42
Opened 2022-12-31 05:55 UTC by EmanuelBorrajero

Por dios con Roniel trabaja muy diferente a mi

2022-12-31 15:32 UTC, yosbel-penate commented
nadie trabaja igual, acostumbrate, es trabajo en equipo, la sinergia se alcanza con el tiempo, como testeo esto

2022-12-31 16:50 UTC, EmanuelBorrajero commented
manage.py makemigrations 
mana.py migrate 
manage.py runserver 
url
http://127.0.0.1:8000/metrics/listscale/

2022-12-31 19:18 UTC, yosbel-penate commented
Arreglar esta url http://127.0.0.1:8000/metrics/listscale/ si la lista es de estcalas por que no poner http://127.0.0.1:8000/metrics/scale/list/

2022-12-31 19:25 UTC, yosbel-penate requested changes
Revisar los comentarios

2022-12-31 22:03 UTC, EmanuelBorrajero commented
ya arregle las urls

2022-12-31 22:48 UTC, yosbel-penate approved these changes

2022-12-31 22:49 UTC, yosbel-penate commented
Esta branch tiene conflictos

2022-12-31 23:16 UTC, yosbel-penate requested changes
No me funciona cuando le hago merge con master,

2023-01-01 18:49 UTC, Roniel1510 commented
ya puede revisar el pullreques

2023-01-01 19:36 UTC, yosbel-penate approved these changes

2023-01-01 19:36 UTC, merged